spring:
  application:
    name: device-hub
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/devicehub}
    username: ${DB_USERNAME:devicehub}
    password: ${DB_PASSWORD:devicehub}
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
