spring:
  application:
    name: device-hub
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/devicehub}
    username: ${DB_USERNAME:devicehub}
    password: ${DB_PASSWORD:devicehub}
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 205MB

devicehub:
  adb:
    path: ${ADB_PATH:}
  storage:
    apk-path: ${APK_STORAGE_PATH:storage/apks}
