CREATE TABLE IF NOT EXISTS device (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    type VARCHAR(20) NOT NULL,
    manufacturer VARCHAR(255) NOT NULL,
    model_name VARCHAR(255) NOT NULL,
    os_version VARCHAR(255),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT device_type_check CHECK (type IN ('PHONE', 'TABLET'))
);

ALTER TABLE device ADD COLUMN IF NOT EXISTS serial_number VARCHAR(255);

CREATE UNIQUE INDEX IF NOT EXISTS uk_device_serial_number
    ON device (serial_number)
    WHERE serial_number IS NOT NULL;

CREATE TABLE IF NOT EXISTS device_deployment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id BIGINT NOT NULL REFERENCES device(id),
    hospital_name VARCHAR(255) NOT NULL,
    deployment_type VARCHAR(30) NOT NULL,
    deployed_at TIMESTAMP NOT NULL,
    returned_at TIMESTAMP,
    note TEXT,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT device_deployment_type_check
        CHECK (deployment_type IN ('HOSPITAL_LOAN', 'HOSPITAL_DEDICATED'))
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_device_active_deployment
    ON device_deployment (device_id)
    WHERE returned_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_device_deployment_history
    ON device_deployment (device_id, deployed_at DESC);

CREATE TABLE IF NOT EXISTS device_project (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id BIGINT NOT NULL REFERENCES device(id),
    project_name VARCHAR(255) NOT NULL,
    package_name VARCHAR(255),
    installed_version VARCHAR(100),
    latest_version VARCHAR(100),
    last_updated_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_device_project_device
    ON device_project (device_id);
