CREATE TABLE IF NOT EXISTS device (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    type VARCHAR(20) NOT NULL,
    manufacturer VARCHAR(255) NOT NULL,
    model_name VARCHAR(255) NOT NULL,
    os_version VARCHAR(255),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT device_type_check CHECK (type IN ('PHONE', 'TABLET'))
);

ALTER TABLE device ADD COLUMN IF NOT EXISTS serial_number VARCHAR(255);

CREATE UNIQUE INDEX IF NOT EXISTS uk_device_serial_number
    ON device (serial_number)
    WHERE serial_number IS NOT NULL;

CREATE TABLE IF NOT EXISTS device_deployment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id BIGINT NOT NULL REFERENCES device(id),
    hospital_name VARCHAR(255) NOT NULL,
    deployment_type VARCHAR(30) NOT NULL,
    deployed_at TIMESTAMP NOT NULL,
    returned_at TIMESTAMP,
    note TEXT,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT device_deployment_type_check
        CHECK (deployment_type IN ('HOSPITAL_LOAN', 'HOSPITAL_DEDICATED'))
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_device_active_deployment
    ON device_deployment (device_id)
    WHERE returned_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_device_deployment_history
    ON device_deployment (device_id, deployed_at DESC);

CREATE TABLE IF NOT EXISTS device_project (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id BIGINT NOT NULL REFERENCES device(id),
    project_name VARCHAR(255) NOT NULL,
    package_name VARCHAR(255),
    installed_version VARCHAR(100),
    latest_version VARCHAR(100),
    last_updated_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_device_project_device
    ON device_project (device_id);

CREATE TABLE IF NOT EXISTS project (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    code VARCHAR(100) NOT NULL UNIQUE,
    description TEXT,
    manager VARCHAR(255),
    status VARCHAR(30) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT project_status_check
        CHECK (status IN ('PLANNING', 'DEVELOPMENT', 'OPERATING', 'SUSPENDED', 'COMPLETED'))
);

CREATE TABLE IF NOT EXISTS device_project_assignment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id BIGINT NOT NULL REFERENCES device(id),
    project_id BIGINT NOT NULL REFERENCES project(id),
    assigned_at TIMESTAMP NOT NULL,
    ended_at TIMESTAMP,
    note TEXT,
    created_at TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_device_active_project_assignment
    ON device_project_assignment (device_id)
    WHERE ended_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_project_assignment_project
    ON device_project_assignment (project_id, assigned_at DESC);

CREATE TABLE IF NOT EXISTS project_network (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES project(id),
    environment_type VARCHAR(30) NOT NULL,
    name VARCHAR(255) NOT NULL,
    api_url VARCHAR(1000),
    socket_url VARCHAR(1000),
    description TEXT,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT project_network_environment_check
        CHECK (environment_type IN ('ISO', 'MFDS', 'DEVELOPMENT', 'BUSINESS'))
);

CREATE INDEX IF NOT EXISTS idx_project_network_project
    ON project_network (project_id);

CREATE TABLE IF NOT EXISTS project_apk (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES project(id),
    version VARCHAR(100) NOT NULL,
    version_code BIGINT NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    file_path VARCHAR(1500) NOT NULL,
    environment_type VARCHAR(30) NOT NULL,
    release_note TEXT,
    uploaded_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT project_apk_environment_check
        CHECK (environment_type IN ('ISO', 'MFDS', 'DEVELOPMENT', 'BUSINESS'))
);

CREATE INDEX IF NOT EXISTS idx_project_apk_latest
    ON project_apk (project_id, environment_type, uploaded_at DESC);
